const PAGES = [
  ["websites", "/websites", "Websites", "Websites", "page"],
  ["websites-connect", "/websites/connect", "Connect website", "Websites", "page"],
  ["seo", "/seo", "SEO hub", "SEO", "page"],
  ["seo-bot", "/seo-bot", "SEO Bot", "SEO", "tool"],
  ["seo-overview", "/seo/overview", "Overview", "SEO", "page"],
  ["seo-basic-info", "/seo/basic-info", "Basic Info", "SEO", "page"],
  ["seo-seo-bot", "/seo/seo-bot", "SEO Bot", "SEO", "tool"],
  ["seo-crawl-stats", "/seo/crawl-stats", "Crawl Stats", "Technical SEO", "tool"],
  ["seo-content-pruning", "/seo/content-pruning", "Content Pruning", "Technical SEO", "tool"],
  ["seo-canonical", "/seo/canonical", "Canonical Tag", "Technical SEO", "tool"],
  ["seo-404-finder", "/seo/404-finder", "404 URL Finder", "Technical SEO", "tool"],
  ["seo-technical-audit", "/seo/technical-audit", "Technical SEO Audit", "Technical SEO", "tool"],
  ["seo-cms-deploy", "/seo/cms-deploy", "Deploy", "Technical SEO", "tool"],
  ["seo-technical-audit-report", "/seo/technical-audit-report", "Technical SEO Audit Report", "Technical SEO", "tool"],
  ["seo-on-page", "/seo/on-page", "On Page SEO", "On Page SEO", "page"],
  ["seo-meta-tags-fixing", "/seo/meta-tags-fixing", "Meta Tags Fixing", "On Page SEO", "tool"],
  ["seo-keyword-placement", "/seo/keyword-placement", "Keyword Placement Naturally", "On Page SEO", "tool"],
  ["seo-internal-link", "/seo/internal-link", "Internal Linking", "On Page SEO", "tool"],
  ["seo-heading-structure", "/seo/heading-structure", "Heading Issue", "On Page SEO", "tool"],
  ["seo-schema-markup", "/seo/schema-markup", "Schema Markup", "On Page SEO", "tool"],
  ["seo-content-generator", "/seo/content-generator", "Content Generator", "Content Tuner", "tool"],
  ["seo-topical-map", "/seo/topical-map", "Topical Map", "Content Tuner", "tool"],
  ["seo-gsc-content-gap", "/seo/gsc-content-gap", "GSC Content Gap", "Content Tuner", "tool"],
  ["seo-featured-snippets", "/seo/featured-snippets", "Featured Snippets", "On Page SEO", "tool"],
  ["seo-pagespeed", "/seo/pagespeed", "PageSpeed", "On Page SEO", "tool"],
  ["seo-ux-ui", "/seo/ux-ui", "UX/UI", "On Page SEO", "tool"],
  ["seo-image-optimization", "/seo/image-optimization", "Image Optimization", "On Page SEO", "tool"],
  ["seo-javascript-code-issue", "/seo/javascript-code-issue", "JavaScript Code Issue", "On Page SEO", "tool"],
  ["seo-duplicate-versions", "/seo/duplicate-versions", "Duplicate Versions of Site", "On Page SEO", "tool"],
  ["seo-orphan-pages", "/seo/orphan-pages", "Orphan Pages", "On Page SEO", "tool"],
  ["seo-canonical-issue", "/seo/canonical-issue", "Canonical Issue", "On Page SEO", "tool"],
  ["seo-eeat-competitor", "/seo/eeat-competitor", "EEAT Competitor", "EEAT", "tool"],
  ["seo-cloud-stack", "/seo/cloud-stack", "Cloud Stack", "Authority Hype", "tool"],
  ["seo-google-stack", "/seo/google-stack", "Google Stack", "Authority Hype", "tool"],
  ["seo-foundational-links", "/seo/foundational-links", "Foundational Links", "Authority Hype", "tool"],
  ["content-tuner", "/content-tuner", "Content Tuner hub", "Content Tuner", "page"],
  ["content-tuner-project", "/content-tuner/project", "Project", "Content Tuner", "tool"],
  ["content-tuner-kw-research", "/content-tuner/kw-research", "KW Research", "Content Tuner", "tool"],
  ["content-tuner-backlinks", "/content-tuner/backlinks", "Backlinks", "Content Tuner", "tool"],
  ["content-tuner-domain-overview", "/content-tuner/domain-overview", "Domain Overview", "Content Tuner", "tool"],
  ["content-tuner-keyword-gap", "/content-tuner/keyword-gap", "Keyword Gap", "Content Tuner", "tool"],
  ["content-tuner-site-audit", "/content-tuner/site-audit", "Technical Audit", "Content Tuner", "tool"],
  ["content-tuner-ai-visibility", "/content-tuner/ai-visibility", "AI Visibility", "Content Tuner", "tool"],
  ["content-tuner-serp-checker", "/content-tuner/serp-checker", "SERP Checker", "Content Tuner", "tool"],
  ["local-seo", "/local-seo", "Local SEO hub", "Local SEO", "page"],
  ["local-seo-gmb-post", "/local-seo/gmb-post", "GMB Post", "Local SEO", "tool"],
  ["local-seo-gmb-audit", "/local-seo/gmb-audit", "GMB Audit", "Local SEO", "tool"],
  ["local-seo-gmb-review", "/local-seo/gmb-review", "GMB Review", "Local SEO", "tool"],
  ["email-marketing", "/email-marketing", "Email Marketing", "Email Marketing", "page"],
  ["social-media-marketing", "/social-media-marketing", "Social Media Marketing", "Social Media Marketing", "page"],
  ["ideal-clients", "/ideal-clients", "Ideal Clients", "Ideal Clients", "page"],
  ["finance", "/finance", "Finance Accounts", "Finance", "page"],
  ["billing", "/billing", "Billing overview", "Billing", "page"],
  ["billing-subscription", "/billing/subscription", "Subscription", "Billing", "page"],
  ["billing-ai-credit", "/billing/ai-generation-credit", "AI Generation Credit", "Billing", "page"],
  ["billing-super-credit", "/billing/authority-credit", "Super Credits", "Billing", "page"],
  ["tickets", "/tickets", "Tickets", "Tickets", "page"],
  ["reports", "/reports", "Reports", "Reports", "page"],
  ["settings", "/settings", "Settings", "Settings", "page"],
  ["settings-users", "/settings/users", "User Settings", "Settings", "page"],
];

function fallbackPageStatuses() {
  const pages = PAGES.map(([id, path, label, group, kind]) => ({
    id,
    path,
    label,
    group,
    kind,
    status: "live",
  }));
  return {
    pages,
    groups: [...new Set(pages.map((page) => page.group))],
    statuses: ["live", "page_maintenance", "tool_maintenance", "coming_soon"],
  };
}

module.exports = { fallbackPageStatuses };
